repos:
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.0 
    hooks:
      - id: djlint
        args: [--reformat]  # --lint to just lint, or --check to check
        types: [html]
  - repo: local
    hooks:
      - id: tidy-html5
        name: tidy-html5
        entry: tidy -quiet -errors
        language: system
        types: [html]

